import "@radix-ui/themes/styles.css";
import { Container, Theme } from "@radix-ui/themes";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import "./globals.css";

import Link from "next/link";
import Logout from "./logout";
import AuthProvider from "../lib/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Theme accentColor="violet">
            <nav>
              {!!session && <Logout />}
              {!session && <Link href="/">Login</Link>}
              {!session && <Link href="/register">Register</Link>}
            </nav>
            <main className="p-5">
              <Container>{children}</Container>
            </main>
          </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
